### ISSUE TITLE
Google Analytics tracking

### ISSUE THREAD

**Issue by TobiasKjrsgaard** [cudim/mooc-plugin#8]
- [x] Embed tracking script in all public page views
- [x] Ignore page views in `wp-admin` directory
- [x] Create a config page using the Settings API
