### ISSUE TITLE
Dansk oversættelse

### ISSUE THREAD

**Issue by TobiasKjrsgaard** [cudim/mooc-plugin#9]
- [x] Oversættelse af `embed.php`
- [x] Oversættelse af `calendar.php`
- [x] Oversættelse af evt. widgets
- [x] Oversættelse af evt. plugins
- [x] Oversættelse af admin interface
- [x] Oversættelse af JavaScripts

…til ITDD MOOC'en

**Comment by TobiasKjrsgaard** [comment]
**TODO**: `wpdiscuz`
